# Generated by Django 4.2.28 on 2026-02-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='listing',
            field=models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property'),
        ),
    ]
